### ISSUE TITLE
什么时候更新呢?在线等着用啊,多谢了

### ISSUE THREAD

**Issue by suntsh** [Xwi/go_uuwiseApi#3]
什么时候更新呢?在线等着用啊,多谢了

**Comment by suntsh** [comment]
这个月底能更新了吗?不想重复造轮子了,在线等待啊

**Comment by Xwi** [comment]
不好意思,最近确实是有点忙的,手上很多工作还未完成, 这个月应该是不会更新的

**Comment by suntsh** [comment]
你能否剥离出代码,我来修改



bigbet@126.com
 
发件人： Quella
发送时间： 2015-03-24 10:52
收件人： Xwi/go_uuwiseApi
抄送： suntsh
主题： Re: [go_uuwiseApi] 什么时候更新呢?在线等着用啊,多谢了 (#3)
不好意思,最近确实是有点忙的,手上很多工作还未完成, 这个月应该是不会更新的

**Comment by suntsh** [comment]
放假这几天,有时间更新了吗?
